name: BuildTools
on:
  push:
  schedule:
    - cron: '0 */4 * * *'  
jobs:
  build:
    name: build hackbin docker image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: build tools docker image
      run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          # echo "$ALI_PASS" | docker login registry.aliyuncs.com -u "$ALI_USER" --password-stdin
          set -x
          docker build -t ysicing/gotools gotools
          docker push ysicing/gotools
          docker build -t ysicing/kubectl kubectl
          docker push ysicing/kubectl
          docker build -t ysicing/k7s -f k7s/Dockerfile . 
          docker tag ysicing/k7s ysicing/k7s:1.16.14
          docker push ysicing/k7s
          docker push ysicing/k7s:1.16.14
          docker build -t ysicing/tools tools
          docker push ysicing/tools
          # docker tag ysicing/tools registry.aliyuncs.com/k7scn/tools
          # docker push registry.aliyuncs.com/k7scn/tools
          docker logout
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        ALI_PASS: ${{ secrets.ALI_PASS }}
        ALI_USER: ${{ secrets.ALI_USER }}        
